# Generated by Django 2.1 on 2019-12-09 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='邮箱')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='主题')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('state', models.CharField(blank=True, choices=[('unread', '未读'), ('read', '已读'), ('solved', '已解决'), ('replied', '已回复'), ('processing', '处理中')], default='unread', max_length=10, null=True, verbose_name='处理情况更新')),
            ],
        ),
    ]
