# Generated by Django 2.1 on 2019-12-09 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, null=True, verbose_name='内容（支持Markdown）')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='message',
            name='qid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
