# Generated by Django 2.1 on 2019-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('authors', models.CharField(default='ADMIN', max_length=200, null=True, verbose_name='作者(逗号隔开)')),
                ('category', models.CharField(choices=[('research', 'Research Dynamics'), ('lecture', 'Lecture News'), ('conference', 'Conference News'), ('default', 'Common News')], default='default', max_length=20, verbose_name='类型')),
                ('created', models.DateField(null=True, verbose_name='日期')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简述')),
                ('body', models.TextField(null=True, verbose_name='正文（支持Markdown语法）')),
                ('url', models.URLField(blank=True, null=True, verbose_name='相关链接')),
                ('avatar', models.ImageField(upload_to='news/avatar/%Y%m%d/', verbose_name='封面')),
                ('image', models.ImageField(blank=True, upload_to='news/image/%Y%m%d/', verbose_name='文中图(多图建议先拼接再上传)')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
