# Generated by Django 2.1 on 2019-11-29 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='authors',
            field=models.CharField(blank=True, default='ADMIN', max_length=200, null=True, verbose_name='作者(逗号隔开)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='news/avatar/%Y%m%d/', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='正文（支持Markdown语法）'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('research', '研究动态'), ('technical ', '技术分享'), ('lecture', '学术讲座及论坛'), ('conference', '外出会议'), ('common', '一般新闻')], default='common', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 9, 2, 34, 47537), null=True, verbose_name='时间'),
        ),
    ]
