# Generated by Django 2.1 on 2019-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191129_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bg_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='bg_b'),
        ),
        migrations.AddField(
            model_name='news',
            name='bg_g',
            field=models.IntegerField(blank=True, null=True, verbose_name='bg_g'),
        ),
        migrations.AddField(
            model_name='news',
            name='bg_r',
            field=models.IntegerField(blank=True, null=True, verbose_name='bg_r'),
        ),
    ]
