# Generated by Django 2.1 on 2019-12-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191210_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='bg_b',
        ),
        migrations.RemoveField(
            model_name='news',
            name='bg_g',
        ),
        migrations.RemoveField(
            model_name='news',
            name='bg_r',
        ),
    ]
