# Generated by Django 2.1 on 2020-02-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200207_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='avatar',
            field=models.ImageField(null=True, upload_to='news/avatar/%Y%m%d/', verbose_name='封面（必填项）'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/image/%Y%m%d/', verbose_name='文中图'),
        ),
    ]
