# Generated by Django 2.1 on 2019-11-25 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('photo', models.URLField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='头衔')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('nan', '无')], default='nan', max_length=6, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('office', models.CharField(blank=True, max_length=20, null=True, verbose_name='办公室')),
                ('biography', models.TextField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('research', models.TextField(blank=True, max_length=500, null=True, verbose_name='研究领域')),
                ('project', models.TextField(blank=True, max_length=500, null=True, verbose_name='主持项目')),
                ('honor', models.TextField(blank=True, max_length=500, null=True, verbose_name='荣誉和奖项')),
            ],
        ),
    ]
