# Generated by Django 2.1 on 2019-11-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='research',
            new_name='interests',
        ),
    ]
