# Generated by Django 2.1 on 2019-11-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20191128_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, choices=[('yes', '在'), ('no', '不在了')], max_length=6, null=True, verbose_name='是否还在组内？'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, choices=[('professor', '教授'), ('phd', '博士研究生'), ('graduate', '硕士研究生'), ('under', '本科生'), ('visit', '访问/交流')], max_length=20, null=True, verbose_name='头衔'),
        ),
    ]
