# Generated by Django 2.1 on 2019-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20191128_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='岗位需求')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='简单说明')),
            ],
        ),
    ]
