# Generated by Django 2.1 on 2019-11-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='photo',
        ),
        migrations.AddField(
            model_name='lab',
            name='image',
            field=models.ImageField(blank=True, upload_to='lab/'),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='members/'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='简单说明'),
        ),
    ]
