# Generated by Django 2.1 on 2019-11-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20191128_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='title_cn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
