# Generated by Django 2.1 on 2019-12-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20191202_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='homepage',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='个人主页'),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(upload_to='members/', verbose_name='头像'),
        ),
    ]
