# Generated by Django 2.1 on 2019-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20191220_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='homepage',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='个人主页'),
        ),
    ]
