# Generated by Django 2.1 on 2020-01-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20191231_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('start', 'title')},
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='members/', verbose_name='头像'),
        ),
    ]
