# Generated by Django 2.1 on 2020-01-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_auto_20200105_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('start', '-title')},
        ),
    ]
