# Generated by Django 2.1 on 2019-11-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('authors', models.CharField(blank=True, max_length=200, null=True, verbose_name='作者(使用分号隔开)')),
                ('journal', models.CharField(blank=True, max_length=100, null=True, verbose_name='期刊')),
                ('accept', models.DateField(blank=True, null=True, verbose_name='接受日期')),
                ('abstract', models.TextField(blank=True, max_length=500, null=True, verbose_name='摘要')),
                ('url', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('image', models.ImageField(blank=True, upload_to='publications/', verbose_name='摘图(多图建议先拼接再上传)')),
            ],
        ),
    ]
