# Generated by Django 2.1 on 2019-11-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20191128_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='name',
            new_name='title',
        ),
    ]
