# Generated by Django 2.1 on 2019-11-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20191128_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='publications/avatar/', verbose_name='封面(期刊截图)'),
        ),
    ]
