# Generated by Django 2.1 on 2019-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20191128_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.URLField(blank=True, null=True, verbose_name='DOI'),
        ),
    ]
