# Generated by Django 2.1 on 2019-11-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_publication_doi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-accept',)},
        ),
    ]
