# Generated by Django 2.1 on 2019-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20191128_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='avatar',
            field=models.ImageField(upload_to='publications/avatar/', verbose_name='封面(期刊截图)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='graph',
            field=models.ImageField(upload_to='publications/graph/', verbose_name='图表(多图建议先拼接再上传)'),
        ),
    ]
