# Generated by Django 2.1 on 2019-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20191128_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(max_length=500, null=True, verbose_name='Reference/Title')),
                ('type', models.CharField(choices=[('journal', 'Journal Articles'), ('patent', 'Patent/Monographs'), ('conference', 'Conference Articles&Abstracts')], default='journal', max_length=20, verbose_name='类型')),
                ('accept', models.DateField(null=True, verbose_name='接收日期(Accepted Date)')),
            ],
            options={
                'ordering': ('-accept',),
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='accept',
            field=models.DateField(null=True, verbose_name='接收日期(Accepted Date)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=200, null=True, verbose_name='作者(使用逗号隔开)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='标题'),
        ),
    ]
