# Generated by Django 2.1 on 2019-11-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_auto_20191128_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='概述'),
        ),
    ]
