# Generated by Django 2.1 on 2019-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_publication_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='avatar',
            field=models.ImageField(upload_to='publications/avatar/', verbose_name='封面'),
        ),
    ]
