# Generated by Django 2.1 on 2019-11-29 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_auto_20191129_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='accept',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 9, 2, 34, 44024), null=True, verbose_name='接收日期(Accepted Date)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(default='unknown,unknown', max_length=200, null=True, verbose_name='作者(至少两位，使用逗号隔开)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='publications/avatar/', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='graph',
            field=models.ImageField(blank=True, upload_to='publications/graph/', verbose_name='图表(多图建议先拼接再上传)'),
        ),
        migrations.AlterField(
            model_name='publist',
            name='accept',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='接收日期(Accepted Date)'),
        ),
    ]
