# Generated by Django 2.1 on 2019-11-29 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_auto_20191129_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='accept',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='接收日期(Accepted Date)'),
        ),
        migrations.AlterField(
            model_name='publist',
            name='accept',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='接收日期(Accepted Date)'),
        ),
    ]
