# Generated by Django 2.1 on 2019-11-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_auto_20191129_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Research Focus')),
                ('field', models.CharField(max_length=200, null=True, verbose_name='所属研究领域')),
                ('body', models.TextField(null=True, verbose_name='正文(支持Markdown语法)')),
                ('graph', models.ImageField(blank=True, upload_to='focus/', verbose_name='图表(多图建议先拼接再上传)')),
                ('graph_desc', models.TextField(blank=True, null=True, verbose_name='图片说明')),
                ('order', models.IntegerField(default='0', null=True, verbose_name='列表顺序(小值显示在前)')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='摘要(支持Markdown语法)'),
        ),
    ]
