# Generated by Django 2.1 on 2019-11-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_auto_20191130_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Major Research Fields')),
                ('icon', models.CharField(default='cloud', max_length=20, null=True, verbose_name='fontawesome icon(http://www.fontawesome.com.cn/faicons/)')),
                ('color', models.CharField(choices=[('aqua', '水绿'), ('black', '黑'), ('blue', '蓝'), ('fuchsia', '紫红'), ('gray', '灰'), ('green', '绿'), ('lime', '浅绿'), ('maroon', '褐'), ('navy', '深蓝'), ('olive', '橄榄'), ('purple', '紫'), ('red', '红'), ('teal', '深青'), ('yellow', '黄')], default='blue', max_length=20, null=True, verbose_name='显示色')),
            ],
        ),
    ]
