# Generated by Django 2.1 on 2019-11-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='简介'),
        ),
    ]
