# Generated by Django 2.1 on 2019-12-01 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_field_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='图片名称')),
                ('desc', models.TextField(null=True, verbose_name='图片描述')),
                ('image', models.ImageField(upload_to='imagegallery/', verbose_name='图片')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Poplink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='标题')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('url', models.URLField(blank=True, null=True, verbose_name='链接')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
