# Generated by Django 2.1 on 2019-12-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0017_galleryimage_poplink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
    ]
