# Generated by Django 2.1 on 2019-12-02 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10, null=True, unique=True, verbose_name='数据集标识(如：et,mlse,edvi,lh等)')),
                ('longname', models.CharField(blank=True, max_length=200, null=True, verbose_name='完整名(如: microwave land surface emissivity)')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='数据简介')),
                ('spatial_coverage', models.CharField(blank=True, max_length=50, null=True, verbose_name='覆盖范围(如: Global, China, East China, Anhui, US, Amazon等)')),
                ('spatial_resolution', models.CharField(blank=True, max_length=200, null=True, verbose_name='空间分辨率(如: 25km, 0.25degree, 37 vertical layers 等信息)')),
                ('date_start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='数据集开始日期(只需要精确填写日期即可)')),
                ('date_end', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='数据集结束日期(只需要精确填写日期即可)')),
                ('temporal_resolution', models.CharField(blank=True, max_length=200, null=True, verbose_name='时间分辨率(如: daily, 3 hours, Monthly 等信息)')),
                ('format', models.CharField(blank=True, max_length=30, null=True, verbose_name='数据格式(如：NetCDF, HDF5, GepTIFF, IMG, Binary, Ascii Formated等)')),
                ('meta', models.TextField(blank=True, null=True, verbose_name='主要数据元(逗号隔开，如：Latent Heating, Rainfall Rate,CSH LH, SLH LH)')),
                ('access', models.FileField(blank=True, upload_to='products/download/', verbose_name='上传示例数据')),
                ('document', models.FileField(blank=True, upload_to='products/documents/', verbose_name='上传说明文档')),
                ('citation', models.TextField(blank=True, null=True, verbose_name='引用')),
                ('faqs', models.TextField(blank=True, null=True, verbose_name='FAQ (支持Markdown语法)')),
            ],
        ),
    ]
