# Generated by Django 2.1 on 2019-12-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('slug',)},
        ),
        migrations.AddField(
            model_name='product',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='products/avatar/', verbose_name='上传封面'),
        ),
    ]
