# Generated by Django 2.1 on 2019-12-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191202_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='版本'),
        ),
    ]
