# Generated by Django 2.1 on 2019-12-03 02:15

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sampleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleimage',
            options={'ordering': ('product',)},
        ),
        migrations.AlterField(
            model_name='sampleimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=products.models.sample_image_path, verbose_name='图片'),
        ),
    ]
