# Generated by Django 2.1 on 2019-12-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191203_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleimage',
            name='scale',
            field=models.CharField(choices=[('orbital', 'Orbit Level'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal'), ('annual', 'Annual'), ('multiyear', 'Multi-year')], default='daily', max_length=10, null=True, verbose_name='Level'),
        ),
    ]
