# Generated by Django 2.1 on 2019-12-03 03:47

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_sampleimage_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(choices=[('orbital', 'Orbit Level'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal'), ('annual', 'Annual'), ('multiyear', 'Multi-year')], default='daily', max_length=10, null=True, verbose_name='Level')),
                ('image', models.ImageField(blank=True, upload_to=products.models.sample_image_path, verbose_name='图片')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.Product')),
            ],
            options={
                'ordering': ('product',),
            },
        ),
        migrations.RemoveField(
            model_name='sampleimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='SampleImage',
        ),
    ]
