# Generated by Django 2.1 on 2019-12-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191203_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='date',
            field=models.DateField(max_length=8, null=True, verbose_name='图片表示的日期(如 20040101,20051231)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='文件名(不包含路径，包含拓展名)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=10, null=True, unique=True, verbose_name='数据集标识,大写缩写(如：ET,MLSE,EDVI,LH等)'),
        ),
    ]
