# Generated by Django 2.1 on 2019-12-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20191204_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='date',
            field=models.CharField(max_length=8, null=True, verbose_name='图片表示的日期(如 20040101,20051231)'),
        ),
    ]
