# Generated by Django 2.1 on 2019-12-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191204_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('date', 'product')},
        ),
    ]
