# Generated by Django 2.1 on 2019-12-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191204_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('product',)},
        ),
    ]
